In [1]:
import numpy as np
arr = np.array([1,2,3])
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 3]


In [4]:
import numpy as np
arr = np.array([1,2,3])
print(type(arr))
print("Array:",arr)
print(arr[0],arr[1])

<class 'numpy.ndarray'>
Array: [1 2 3]
1 2


In [5]:
import numpy as np
arr = np.array([1,2,3])
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(3,)


In [0]:
import numpy as np
l = [1,2,3]
l = [l,l,l]
arr = np.array(l)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [0]:
import numpy as np
l = [1,2,3]
l = [l,l,l]
arr = np.array(l)
print(type(arr))
print(arr.shape)

<class 'numpy.ndarray'>
(3, 3)


In [0]:
import numpy as np
l = [1,2,3]
l = [l,l,l]
l = [l,l,l]
arr = np.array(l)
print(arr)
print(arr.shape)

[[[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]

 [[1 2 3]
  [1 2 3]
  [1 2 3]]]
(3, 3, 3)


In [0]:
import numpy as np
l = [1,2,3]
l = [l,l,l]
l = [l,l,l]
arr = np.array(l)
print(arr)

In [9]:
import numpy as np
arr = np.array([[1,2,3]])
print(arr)
print(arr[0][1])

[[1 2 3]]
2


In [10]:
import numpy as np
arr = np.array([[1,2,3]])
print(arr)
print(arr[0,1])

[[1 2 3]]
2


In [12]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
arr = np.ones((3,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
arr = np.full((3,3),5)
print(arr)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [15]:
arr = np.eye((3))
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
arr = np.random.random((3,3))
print(arr)

[[0.97378817 0.62990678 0.83216135]
 [0.22048537 0.4752398  0.2379163 ]
 [0.26294945 0.33026768 0.5815055 ]]


In [18]:
arr = np.arange(15).reshape(3,5)#range of array from 0 to 15 
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [2]:
arr = np.arange(15).reshape(3,5)#range of array from 0 to 15 
print(arr)
print(arr.ndim)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2


In [3]:
arr = np.arange(15).reshape(3,5)#range of array from 0 to 15 
print(arr)
print(arr.ndim)
print(arr.dtype.name)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
int64


In [4]:
arr = np.arange(15).reshape(3,5)#range of array from 0 to 15 
print(arr)
print(arr.ndim)
print(arr.itemsize)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
8


In [5]:
arr = np.arange(15).reshape(3,5)#range of array from 0 to 15 
print(arr)
print(arr.ndim)
print(type(arr))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
2
<class 'numpy.ndarray'>


In [6]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)


In [9]:
arr = np.array([[1,2,3], [5,6,7], [9,10,11]])
print(arr)
print(arr.shape)

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]]
(3, 3)


In [10]:
arr = np.array([[1,2,3]])
print(arr)
print(arr.shape)

[[1 2 3]]
(1, 3)


In [11]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr[:2, 1:3])

[[2 3]
 [6 7]]


In [15]:
arr = np.array([1,2,3])
print(arr[:0])
print(arr[:1])
print(arr[:2])

[]
[1]
[1 2]


In [19]:
arr = np.array([1,2,3])
print(arr[0:3])
print(arr[1:3])
print(arr[2:3])
print(arr[0:1])
print(arr[0:2])
print(arr[0:3])

[1 2 3]
[2 3]
[3]
[1]
[1 2]
[1 2 3]


In [22]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr[2, 1])
print(arr[:2])
print(arr[0:2])


10
[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [25]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr[:2, 1:3])

[[2 3]
 [6 7]]


print(arr[:2, 1:3]) this means from  

np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
firstly 0th and 1th element of list is selected that is [1,2,3,4], [5,6,7,8] now out of them 1:3 
position is selected i.e from  [1,2,3,4]  [2 3] is selected and from  [5,6,7,8] [6 7] is selected.

In [26]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = arr[1, :]
row_r2 = arr[1:2, :]
print(row_r1)
print(row_r2)

[5 6 7 8]
[[5 6 7 8]]


In [27]:
a = [1,2,3]
print(a[0])
print(a[0:1])

1
[1]


In [28]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = arr[1, :]
row_r2 = arr[1:2, :]
print(row_r1.shape)
print(row_r2.shape)

(4,)
(1, 4)


In [31]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = arr[:, 1]
row_r2 = arr[:, 1:2]
print(row_r1)
print(row_r2)
print(row_r1.shape)
print(row_r2.shape)
print(arr.shape)

[ 2  6 10]
[[ 2]
 [ 6]
 [10]]
(3,)
(3, 1)
(3, 4)


In [32]:
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[[0, 1, 2], [0, 1, 0]])

[1 4 5]


print(arr[[0, 1, 2], [0, 1, 0]]) this statement is equal to 

print(np.array([arr[0,0], arr[1,1], arr[2,0]]))

In [2]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr > 2)

[[False False  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [3]:
arr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(arr[arr > 2])

[ 3  4  5  6  7  8  9 10 11 12]


In [4]:
arr = np.array([1, 2])
print(np.dtype)

arr = np.array([1.0, 2.0])
print(np.dtype)

arr = np.array([1.0,2.0], dtype = np.int64)
print(arr)

<class 'numpy.dtype'>
<class 'numpy.dtype'>
[1 2]


In [5]:
arr = np.array([1, 2])
print(arr.dtype)

arr = np.array([1.0, 2.0])
print(arr.dtype)

arr = np.array([1.0,2.0], dtype = np.int64)
print(arr)

int64
float64
[1 2]


In [11]:
arr_a = np.array([1.0, 2.0])
arr_b = np.array([3.0, 4.0])

print(arr_a + arr_b)
print(np.add(arr_a, arr_b))


[4. 6.]
[4. 6.]


In [12]:

print(arr_b- arr_a)
print(np.subtract(arr_b, arr_a))


[2. 2.]
[2. 2.]


In [13]:

print(arr_b * arr_a)
print(np.multiply(arr_b, arr_a))


[3. 8.]
[3. 8.]


In [14]:

print(arr_b / arr_a)
print(np.divide(arr_b, arr_a))



[3. 2.]
[3. 2.]


In [15]:

print(np.sqrt(arr_a))
print(np.sqrt(arr_b))


[1.         1.41421356]
[1.73205081 2.        ]


In [16]:

print(np.dot(arr_a, arr_b))
print(arr_a.dot(arr_b))


11.0
11.0


In [18]:
arr = np.array([arr_a, arr_b])
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))
print(arr_a.T)

[4. 6.]
[3. 7.]
[1. 2.]


arr_a = np.array([1.0, 2.0])

arr_b = np.array([3.0, 4.0])

for axis  = 0 [3+1 4+2]  which is equal to [4 6] 

and for axis =  1 [1+2 3+4] which is equal to [3 7] 

In [19]:
print(arr.T)

[[1. 3.]
 [2. 4.]]
